# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    container_name: telkom-mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  # mongo-seed:
  #   container_name: telkom-mongo-seed
  #   build: ./mongo-seed
  #   restart: always
  #   depends_on:
  #     - mongo
  #   links:
  #     - mongo

  mongo-express:
    container_name: telkom-mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo

  mysql:
    container_name: telkom-mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
    volumes:
      - ./mysql_init.sql:/docker-entrypoint-initdb.d/init.sql
